#spring.application.name=journalApp
#
##spring.data.mongodb.uri=mongodb://localhost:27017/journaldb //If you are on Spring Boot 4.1.0, the old property spring.data.mongodb.uri is unrecognized and ignored.Fallback to Defaults: Since no valid MongoDB URI or database name is found in your configuration, Spring Boot falls back to its default autoconfiguration, which connects to mongodb://localhost:27017 and uses the default database name test. This is why your journal_entries collection is being created inside the test database.
#
##To direct the application to use the journaldb database, you would update the property name in your
##application.properties
##to use the new prefix:
## For Spring Boot 2.x (such as 2.7.18): use spring.data.mongodb.*
#spring.data.mongodb.uri=mongodb+srv://talibmohammadnaqiansari_db_user:bI18X1NPfklNBvIA@cluster0.tzfznpd.mongodb.net/journaldb?retryWrites=true&w=majority
#spring.data.mongodb.auto-index-creation=true
##through this the indexes are automatically create in database like Journal Entries are created
#
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.springframework.security=DEBUG